### ISSUE TITLE
Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by jbruettcva** [nshobayo/AWS-CLI#1]
so i have the env variables aws_default_profile and aws_profile set to saml.  I am able to pass my credentials and select a role to assume but then receive the following error.

```
Exception in thread "main" com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in thechain
        at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1097)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithSAML(AWSSecurityTokenServiceClient.java:574)
        at AssumeRoleWithOktaSAML.assumeAWSRole(AssumeRoleWithOktaSAML.java:558)
        at AssumeRoleWithOktaSAML.main(AssumeRoleWithOktaSAML.java:614)
```

**Comment by wgregorian** [comment]
Ditto.

**Comment by don-code** [comment]
This happens because of the way the AWS SDK is being initialized. I have a branch ready to go which fixes it, but am waiting for one of my other changes (#7) to merge first.

A temporary workaround is to put garbage characters into the `aws_access_key_id` and `aws_secret_access_key` parameters in the credential file, as these parameters aren't actually used once the SDK initialization is complete.
